-- 1. Create the events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  event TEXT NOT NULL,
  step_index INT,
  step_id TEXT,
  value JSONB,
  time_on_step_ms INT,
  total_time_ms INT,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  ip TEXT,
  country TEXT
);

-- 2. Create indices for performance
CREATE INDEX IF NOT EXISTS idx_events_session ON events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_event   ON events(event);
CREATE INDEX IF NOT EXISTS idx_events_step    ON events(step_id);
CREATE INDEX IF NOT EXISTS idx_events_date    ON events(created_at);

-- 3. Row Level Security (RLS)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (front-end tracking)
DROP POLICY IF EXISTS "allow_insert_events" ON events;
CREATE POLICY "allow_insert_events" ON events
FOR INSERT TO anon, authenticated
WITH CHECK (
  event IN (
    'session_start','session_end','step_view','step_complete',
    'step_back','step_abandon','option_select','option_deselect',
    'slider_change','slider_final','result_view','result_cta_click','utm_captured'
  )
);

-- Allow reads only for authenticated admins
DROP POLICY IF EXISTS "allow_select_events" ON events;
CREATE POLICY "allow_select_events" ON events
FOR SELECT TO authenticated
USING (auth.role() = 'authenticated');

-- 4. Create the RPC function to aggregate admin metrics
CREATE OR REPLACE FUNCTION get_admin_metrics(from_date TIMESTAMPTZ, to_date TIMESTAMPTZ)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_total_sessions INT;
  v_total_completions INT;
  v_cta_clicks INT;
  v_step_funnel JSONB;
  v_dropoff_by_step JSONB;
  v_avg_time_by_step JSONB;
  v_option_distribution JSONB;
  v_weight_distribution JSONB;
  v_sessions_by_day JSONB;
  v_top_utm_sources JSONB;
  v_avg_total_time FLOAT;
  v_result JSONB;
BEGIN
  -- 1. Total sessions
  SELECT COUNT(DISTINCT session_id) INTO v_total_sessions
  FROM events WHERE event = 'session_start' AND created_at BETWEEN from_date AND to_date;

  -- 2. Total completions
  SELECT COUNT(DISTINCT session_id) INTO v_total_completions
  FROM events WHERE event = 'result_view' AND created_at BETWEEN from_date AND to_date;

  -- 3. CTA clicks
  SELECT COUNT(DISTINCT session_id) INTO v_cta_clicks
  FROM events WHERE event = 'result_cta_click' AND created_at BETWEEN from_date AND to_date;

  -- 4. Unified Step Funnel (Views, Completions, Time, Top Answer)
  SELECT COALESCE(jsonb_agg(row_to_json(t)), '[]'::jsonb) INTO v_step_funnel
  FROM (
    WITH step_stats AS (
      SELECT 
        v.step_index,
        v.step_id,
        COUNT(DISTINCT v.session_id) as viewed,
        COUNT(DISTINCT c.session_id) as completed,
        ROUND((100.0 * (1 - COALESCE(COUNT(DISTINCT c.session_id), 0)::numeric / NULLIF(COUNT(DISTINCT v.session_id), 0)::numeric))::numeric, 1) as dropoff_pct,
        ROUND((AVG(c.time_on_step_ms)/1000.0)::numeric, 1) as avg_seconds
      FROM events v
      LEFT JOIN events c ON c.session_id = v.session_id AND c.step_id = v.step_id AND c.event = 'step_complete'
      WHERE v.event = 'step_view' AND v.created_at BETWEEN from_date AND to_date
      GROUP BY v.step_index, v.step_id
    ),
    popular_answers AS (
      SELECT DISTINCT ON (step_id) step_id, value, COUNT(*) as answer_count
      FROM events 
      WHERE event IN ('option_select', 'slider_final') AND value IS NOT NULL AND value::text != 'null' AND created_at BETWEEN from_date AND to_date
      GROUP BY step_id, value
      ORDER BY step_id, answer_count DESC
    )
    SELECT 
      s.step_index,
      s.step_id,
      s.viewed,
      s.completed,
      s.dropoff_pct,
      s.avg_seconds,
      pa.value as top_answer
    FROM step_stats s
    LEFT JOIN popular_answers pa ON pa.step_id = s.step_id
    ORDER BY s.step_index ASC
  ) t;

  -- (Removed deprecated individual queries 5, 6, 7 to unify in query 4 above)

  -- 8. Weight distribution
  SELECT COALESCE(jsonb_agg(row_to_json(t)), '[]'::jsonb) INTO v_weight_distribution
  FROM (
    SELECT value as weight, COUNT(*) as count
    FROM events WHERE event = 'slider_final' AND step_id = 'current_weight' AND created_at BETWEEN from_date AND to_date
    GROUP BY value
  ) t;

  -- 9. Sessions by day
  SELECT COALESCE(jsonb_agg(row_to_json(t)), '[]'::jsonb) INTO v_sessions_by_day
  FROM (
    SELECT DATE(created_at) as date, COUNT(DISTINCT session_id) as sessions
    FROM events WHERE event = 'session_start' AND created_at BETWEEN from_date AND to_date
    GROUP BY date ORDER BY date
  ) t;

  -- 10. Top UTM sources
  SELECT COALESCE(jsonb_agg(row_to_json(t)), '[]'::jsonb) INTO v_top_utm_sources
  FROM (
    SELECT meta->>'utm_source' as source, meta->>'utm_campaign' as campaign, COUNT(*) as sessions
    FROM events WHERE event = 'session_start' AND meta->>'utm_source' IS NOT NULL AND created_at BETWEEN from_date AND to_date
    GROUP BY source, campaign ORDER BY sessions DESC LIMIT 10
  ) t;

  -- 11. Avg total time to CTA
  SELECT ROUND((AVG(total_time_ms)/1000.0)::numeric, 0) INTO v_avg_total_time
  FROM events WHERE event = 'result_cta_click' AND created_at BETWEEN from_date AND to_date;

  -- Construct final JSON response
  SELECT json_build_object(
    'summary', json_build_object(
      'totalSessions', COALESCE(v_total_sessions, 0),
      'totalCompletions', COALESCE(v_total_completions, 0),
      'completionRate', CASE WHEN v_total_sessions > 0 THEN ROUND((v_total_completions::numeric / v_total_sessions::numeric * 100)::numeric, 1) ELSE 0 END,
      'ctaClicks', COALESCE(v_cta_clicks, 0),
      'ctaRate', CASE WHEN v_total_sessions > 0 THEN ROUND((v_cta_clicks::numeric / v_total_sessions::numeric * 100)::numeric, 1) ELSE 0 END,
      'avgTimeToCtaSeconds', COALESCE(v_avg_total_time, 0)
    ),
    'stepFunnel', COALESCE(v_step_funnel, '[]'::jsonb),
    'weightDistribution', COALESCE(v_weight_distribution, '[]'::jsonb),
    'sessionsByDay', COALESCE(v_sessions_by_day, '[]'::jsonb),
    'topUtmSources', COALESCE(v_top_utm_sources, '[]'::jsonb)
  ) INTO v_result;

  RETURN v_result;
END;
$$;
